manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tps43-remote
      url-base: https://github.com/klitospapae
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: tps43_zmk
      remote: tps43-remote
      revision: main
  self:
    path: config
